server:
  port: 7373
spring:
  datasource:
    password: Temp1234
    url: jdbc:mysql://localhost:3306/myproject
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  application:
    name: fooditem-service
    
eureka:
  client:
    register-with-eureka: false
    
    fetch-registry: true
    
    
  instance:
    hostname: localhost
    instance-id: localhost